/// A reservation on a Nestly listing — either a **visit** (a scheduled
/// consultation/viewing at a single date & time) or a **stay** (a dated booking
/// with a check-in and check-out, for summer vacation rentals).
///
/// This is the backbone of the management side of the product: the calendar,
/// the host dashboard and the seeker's trips all read from reservations.
enum ReservationType { visit, stay }

extension ReservationTypeX on ReservationType {
  String get id => name;

  String get label => switch (this) {
    ReservationType.visit => 'Visit',
    ReservationType.stay => 'Stay',
  };

  String get verb => switch (this) {
    ReservationType.visit => 'Book a visit',
    ReservationType.stay => 'Reserve dates',
  };

  static ReservationType fromId(String? id) =>
      id == 'stay' ? ReservationType.stay : ReservationType.visit;
}

/// The full lifecycle the `reservations` table allows. `rejected` and `expired`
/// arrived with the reservation module migration; before they existed here the
/// parser folded both into `pending`, so a seeker whose request had been turned
/// down still saw "Pending" forever.
enum ReservationStatus {
  pending,
  confirmed,
  rejected,
  cancelled,
  expired,
  completed,
}

extension ReservationStatusX on ReservationStatus {
  String get id => name;

  String get label => labelFor(false);

  String labelFor(bool french) => switch (this) {
    ReservationStatus.pending => french ? 'En attente' : 'Pending',
    ReservationStatus.confirmed => french ? 'Confirmée' : 'Confirmed',
    ReservationStatus.rejected => french ? 'Refusée' : 'Declined',
    ReservationStatus.cancelled => french ? 'Annulée' : 'Cancelled',
    ReservationStatus.expired => french ? 'Expirée' : 'Expired',
    ReservationStatus.completed => french ? 'Terminée' : 'Completed',
  };

  /// Holds the dates. Only these two block a listing's calendar — the same set
  /// the Postgres exclusion constraint uses.
  bool get isActive =>
      this == ReservationStatus.pending || this == ReservationStatus.confirmed;

  /// The request is finished either way; nothing more will happen to it.
  bool get isClosed => !isActive;

  /// An outcome the traveller should be told about, with a reason attached.
  bool get isRefusal =>
      this == ReservationStatus.rejected ||
      this == ReservationStatus.cancelled;

  static ReservationStatus fromId(String? id) => switch (id) {
    'confirmed' => ReservationStatus.confirmed,
    'rejected' => ReservationStatus.rejected,
    'cancelled' => ReservationStatus.cancelled,
    'expired' => ReservationStatus.expired,
    'completed' => ReservationStatus.completed,
    _ => ReservationStatus.pending,
  };
}

class Reservation {
  const Reservation({
    required this.id,
    required this.propertyId,
    required this.propertyTitle,
    required this.propertyCity,
    required this.guestId,
    required this.guestName,
    required this.type,
    required this.start,
    required this.createdAt,
    this.end,
    this.guests = 1,
    this.status = ReservationStatus.pending,
    this.note,
    this.estimatedTotal,
    this.reference,
    this.expiresAt,
    this.cancellationReason,
  });

  final String id;
  final String propertyId;
  final String propertyTitle;
  final String propertyCity;
  final String guestId;
  final String guestName;
  final ReservationType type;

  /// Visit: the date & time of the viewing. Stay: the check-in date.
  final DateTime start;

  /// Stay only: the check-out date.
  final DateTime? end;

  final int guests;
  final ReservationStatus status;
  final String? note;
  final double? estimatedTotal;
  final DateTime createdAt;

  /// Human-friendly booking code (`NBK-1A2B3C`) generated by the database. Both
  /// the traveller and the agency quote this when they talk to each other.
  final String? reference;

  /// When the 48 h soft lock on a pending request runs out. Past this the
  /// agency loses the request and the dates go back on sale.
  final DateTime? expiresAt;

  /// Why the agency declined or cancelled. The dashboard makes this mandatory,
  /// so there is always something to show once the status is a refusal.
  final String? cancellationReason;

  /// Time left before the soft lock lapses. `Duration.zero` once it has.
  Duration get remainingHold {
    final e = expiresAt;
    if (e == null || status != ReservationStatus.pending) return Duration.zero;
    final left = e.difference(DateTime.now());
    return left.isNegative ? Duration.zero : left;
  }

  /// A pending row whose hold has lapsed is treated as expired on sight, the
  /// same read-time correction the dashboard applies — the background job that
  /// persists the flip only runs every 15 minutes.
  ReservationStatus get effectiveStatus {
    if (status == ReservationStatus.pending &&
        expiresAt != null &&
        remainingHold == Duration.zero) {
      return ReservationStatus.expired;
    }
    return status;
  }

  /// Number of nights for a stay (0 for a visit).
  int get nights {
    final e = end;
    if (type != ReservationType.stay || e == null) return 0;
    return e.difference(DateTime(start.year, start.month, start.day)).inDays;
  }

  /// True when the reservation's date is today or in the future.
  bool get isUpcoming {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    return !start.isBefore(today);
  }

  /// Every calendar day this reservation occupies (inclusive check-in →
  /// exclusive check-out for a stay; a single day for a visit).
  List<DateTime> get occupiedDays {
    final first = DateTime(start.year, start.month, start.day);
    if (type == ReservationType.visit || end == null) return [first];
    final days = <DateTime>[];
    for (var d = first; d.isBefore(end!); d = d.add(const Duration(days: 1))) {
      days.add(DateTime(d.year, d.month, d.day));
    }
    return days.isEmpty ? [first] : days;
  }

  Reservation copyWith({
    ReservationStatus? status,
    String? cancellationReason,
  }) => Reservation(
    id: id,
    propertyId: propertyId,
    propertyTitle: propertyTitle,
    propertyCity: propertyCity,
    guestId: guestId,
    guestName: guestName,
    type: type,
    start: start,
    end: end,
    guests: guests,
    status: status ?? this.status,
    note: note,
    estimatedTotal: estimatedTotal,
    createdAt: createdAt,
    reference: reference,
    expiresAt: expiresAt,
    cancellationReason: cancellationReason ?? this.cancellationReason,
  );

  Map<String, dynamic> toMap() => {
    'id': id,
    'property_id': propertyId,
    'property_title': propertyTitle,
    'property_city': propertyCity,
    'guest_id': guestId,
    'guest_name': guestName,
    'type': type.id,
    'start': start.toIso8601String(),
    'end': end?.toIso8601String(),
    'guests': guests,
    'status': status.id,
    'note': note,
    'estimated_total': estimatedTotal,
    'created_at': createdAt.toIso8601String(),
    'reference': reference,
    'expires_at': expiresAt?.toIso8601String(),
    'cancellation_reason': cancellationReason,
  };

  factory Reservation.fromMap(Map<String, dynamic> map) => Reservation(
    id: map['id'].toString(),
    propertyId: map['property_id']?.toString() ?? '',
    propertyTitle: map['property_title'] as String? ?? '',
    propertyCity: map['property_city'] as String? ?? '',
    guestId: map['guest_id'] as String? ?? '',
    guestName: map['guest_name'] as String? ?? '',
    type: ReservationTypeX.fromId(map['type'] as String?),
    start: DateTime.parse(map['start'] as String),
    end: (map['end'] as String?) == null
        ? null
        : DateTime.parse(map['end'] as String),
    guests: (map['guests'] as num?)?.toInt() ?? 1,
    status: ReservationStatusX.fromId(map['status'] as String?),
    note: map['note'] as String?,
    estimatedTotal: (map['estimated_total'] as num?)?.toDouble(),
    createdAt:
        DateTime.tryParse(map['created_at'] as String? ?? '') ?? DateTime.now(),
    reference: map['reference'] as String?,
    expiresAt: DateTime.tryParse(map['expires_at'] as String? ?? ''),
    cancellationReason: map['cancellation_reason'] as String?,
  );
}
